RCOSDP/weko

- modules/weko-admin/weko_admin/static/js/weko_admin/custom_report.js
Display period with single day instead of displaying "Day - Day"
> Correct day in custom report

- modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/detail.html
- modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/file_details.html
/modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/detail.html
/modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/file_details.html:
Addthis ID is changed from ra-5137aff66ad9c2a1 to ra-5d8af23e9a3a2633.
> Changed account ID.

- modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/box/versions.html
> table display fix

- modules/weko-itemtypes-ui/weko_itemtypes_ui/admin.py
- modules/weko-records/weko_records/api.py
- modules/weko-records/weko_records/models.py
- modules/weko-records/weko_records/utils.py
> Update code for not upgrade version of ItemType in small change

- modules/weko-itemtypes-ui/weko_itemtypes_ui/static/js/weko_itemtypes_ui/create_itemtype.js
- modules/weko-itemtypes-ui/weko_itemtypes_ui/static/js/weko_itemtypes_ui/jsonschemaeditor.js
> weko#21538: Support enble click on Localization button

- modules/weko-items-ui/weko_items_ui/utils.py
- modules/weko-search-ui/weko_search_ui/admin.py
- modules/weko-search-ui/weko_search_ui/config.py
- modules/weko-search-ui/weko_search_ui/utils.py
> weko#22359 - Fixbug can't import if has \n in content, change #n to, fixbug suffix cnri, doi

- modules/weko-itemtypes-ui/weko_itemtypes_ui/static/js/weko_itemtypes_ui/create_itemtype.js
- modules/weko-itemtypes-ui/weko_itemtypes_ui/static/js/weko_itemtypes_ui/jsonschemaeditor.js
Hi reviewer,
Pls help to review. Thanks
> weko#22538: Implement the behavior of child options

- modules/weko-itemtypes-ui/weko_itemtypes_ui/static/js/weko_itemtypes_ui/create_itemtype.js
- modules/weko-itemtypes-ui/weko_itemtypes_ui/templates/weko_itemtypes_ui/admin/create_itemtype.html
> weko#23281: Add loading icon to MetadataScreen

- modules/weko-itemtypes-ui/weko_itemtypes_ui/static/js/weko_itemtypes_ui/jsonschemaeditor.js
> weko#23289 - Fixbug show first vertical bar - dev40

- modules/weko-deposit/weko_deposit/api.py
- modules/weko-items-ui/weko_items_ui/utils.py
- modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/body_contents.html
- modules/weko-records-ui/weko_records_ui/views.py
- modules/weko-workflow/weko_workflow/templates/weko_workflow/record_detail.html
> Fix/sp56 file option improvement  dev37

- modules/weko-search-ui/weko_search_ui/static/templates/weko_search_ui/indexlist.html
modules/weko-search-ui/weko_search_ui/static/templates/weko_search_ui/indexlist.html
> #24514  3.2.1. 機関連絡先の表示についての対応内容確認

- modules/weko-theme/weko_theme/templates/weko_theme/body_index.html
> #24105 miCheckerによる評価結果に応じたWEKO3の改修 ver1.1

- modules/weko-records-ui/weko_records_ui/config.py
- modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/output_detail_data.html
update 
modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/output_detail_data.html
modules/weko-records-ui/weko_records_ui/config.py
> #24934 アイテム詳細画面にて言語指定に応じた値を表示

- modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/output_detail_data.html
update modules/weko-records-ui/weko_records_ui/templates/weko_records_ui/output_detail_data.html
> #24934 アイテム詳細画面にて言語指定に応じた値を表示する機能

- modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
update 
modules/weko-theme/weko_theme/static/js/weko_theme/search_detail.js
> #24936 インデックス検索画面表示修正

- modules/invenio-oaiserver/invenio_oaiserver/receivers.py
- modules/weko-deposit/weko_deposit/api.py
- modules/weko-deposit/weko_deposit/receivers.py
- scripts/demo/replace_indexpath.py
jc-niirdc-mig-rc-aに登録された一部のアイテムがインデックスとの紐づけが消失&アイテム検索でもヒットしなくなった問題のデータ修正を行う
> SP68 - Replace index path by id - scripts

- modules/weko-admin/weko_admin/api.py
- modules/weko-admin/weko_admin/config.py
- modules/weko-admin/weko_admin/tasks.py
- modules/weko-search-ui/weko_search_ui/admin.py
- modules/weko-search-ui/weko_search_ui/static/js/weko_search_ui/import.js
- modules/weko-search-ui/weko_search_ui/tasks.py
- modules/weko-search-ui/weko_search_ui/utils.py
- scripts/instance.cfg
> weko#26164 SP70: Fixbug celery stop after import if lifetime > consumer_timeout

- modules/weko-deposit/weko_deposit/api.py
- modules/weko-deposit/weko_deposit/rest.py
- modules/weko-items-ui/weko_items_ui/views.py
- modules/weko-records-ui/weko_records_ui/fd.py
- modules/weko-search-ui/weko_search_ui/utils.py
- modules/weko-workflow/weko_workflow/api.py
- modules/weko-workflow/weko_workflow/utils.py
- modules/weko-workflow/weko_workflow/views.py
> DB tranasction fix 

- modules/weko-index-tree/weko_index_tree/api.py
- modules/weko-index-tree/weko_index_tree/utils.py
weko#29114 fix all index delete bug
> fix all index delete bug

- modules/weko-search-ui/weko_search_ui/config.py
- modules/weko-search-ui/weko_search_ui/utils.py
Retry if there are OperationalError when export all items.
> weko#29105 retry if there are OperationalError

- modules/weko-itemtypes-ui/weko_itemtypes_ui/admin.py
- modules/weko-itemtypes-ui/weko_itemtypes_ui/static/js/weko_itemtypes_ui/create_itemtype.js
- modules/weko-itemtypes-ui/weko_itemtypes_ui/templates/weko_itemtypes_ui/admin/create_itemtype.html
- modules/weko-itemtypes-ui/weko_itemtypes_ui/templates/weko_itemtypes_ui/admin/error.html
- packages.txt
・update
modules/weko-itemtypes-ui/weko_itemtypes_ui/admin.py
modules/weko-itemtypes-ui/weko_itemtypes_ui/static/js/weko_itemtypes_ui/create_itemtype.js
modules/weko-itemtypes-ui/weko_itemtypes_ui/templates/weko_itemtypes_ui/admin/create_itemtype.html
modules/weko-itemtypes-ui/weko_itemtypes_ui/templates/weko_itemtypes_ui/admin/error.html
packages.txt
> #24935 アイテムタイプのインポート・エクスポート機能

- modules/invenio-accounts/invenio_accounts/admin.py
Fix permission setting in admin/user
> Fix permission setting for SystemAdministrator

- modules/weko-deposit/weko_deposit/api.py
weko#30281 fix item update issue
> weko#30281 fix item update issue

- modules/invenio-files-rest/invenio_files_rest/admin.py
- modules/weko-records-ui/weko_records_ui/utils.py
weko#30890 file physical delete
> weko#30890 file physical delete

- modules/weko-authors/weko_authors/views.py
@mhaya
#31461 アイテム登録時に/authors/inputで流用入力を行った際にエラーが生じる件に関して、修正を行いました。
どうぞよろしくお願いいたします。
> fix #31461

- modules/invenio-oaiserver/invenio_oaiserver/response.py
weko#31564 fix OAI-PMH output bug
> weko#31564 fix oai-pmh output bug

- modules/weko-records-ui/weko_records_ui/utils.py
based on latest release branch.
Value of -1 will be set when value error occurs
> Value of -1 will be set when value error occurs

- modules/weko-gridlayout/weko_gridlayout/static/css/weko_gridlayout/widget.item.css
- modules/weko-theme/weko_theme/static/css/weko_theme/widget.css
overwrite cursor: move with cursor: default for widget images
> Widget hover cursor fix to default

- modules/weko-search-ui/tests/conftest.py
- modules/weko-search-ui/tests/test_tasks.py
- modules/weko-search-ui/tests/test_utils.py
> Test code update weko search UI

- modules/weko-search-ui/tests/conftest.py
- modules/weko-search-ui/tests/test_utils.py
- modules/weko-search-ui/weko_search_ui/utils.py
> fix issue34535

- modules/weko-items-ui/weko_items_ui/static/js/weko_items_ui/app.js
- scripts/demo/properties/files.py
- scripts/demo/update_item_type.py
> input open access bug fixed

- modules/weko-bulkupdate/tests/test_views.py
- modules/weko-bulkupdate/tests/test_weko_bulkupdate.py
> add tests weko_bulkupdate

- docker-compose.arm64.yml
- docker-compose.full.yml
- docker-compose.sentinel.yml
- docker-compose.withHandle.yml
- docker-compose.yml
- docker-compose2.yml
@mhaya 
RabbitMQのタイムアウトの設定をdocker-composeファイルに追記いたしました。
ご確認の程、よろしくお願いいたします。
> add rabbitmq consumer_timeout

- scripts/demo/properties/__init__.py
> Fix register_properties.py bug

- modules/weko-authors/weko_authors/views.py
Fix arguments of func update_items_by_authorInfo.
> Fix merge error in weko_authors module

- nginx/login.php
- nginx/weko.conf
Add flag for not check `wekoSocietyAffiliation` on WEKO3 shib login.
> HIROBA_MIG-1830

- modules/invenio-oaiserver/invenio_oaiserver/response.py
- modules/invenio-oaiserver/invenio_oaiserver/utils.py
- modules/invenio-stats/invenio_stats/config.py
- modules/invenio-stats/invenio_stats/queries.py
- modules/weko-deposit/weko_deposit/api.py
- modules/weko-index-tree/weko_index_tree/utils.py
- modules/weko-items-ui/weko_items_ui/utils.py
- modules/weko-records-ui/tests/test_utils.py
- modules/weko-records-ui/weko_records_ui/permissions.py
- modules/weko-records-ui/weko_records_ui/utils.py
* Fix HIROBA_MIG-1931
* Fix HIROBA_MIG-1933
> V0.9.26 hiroba

- modules/weko-search-ui/tests/test_query.py
- modules/weko-search-ui/weko_search_ui/config.py
- modules/weko-search-ui/weko_search_ui/query.py
> WEKO#39477 Fixed the processing of the language option "Other" in advanced search conditions.

- modules/weko-gridlayout/tests/test_views.py
f19b8da88404eebbeb24f2d4d62a68043556a681 の修正の影響で失敗していた単体テストを修正しました
> fix tests in pr#1426

- modules/weko-accounts/tests/test_views.py
> fix-test_views.py

- modules/weko-workflow/weko_workflow/static/js/weko_workflow/workflow_detail.js
> review fix 51930
